Login-AzureRMAccount

Select-AzureRMSubscription -subscriptionname "Enter here your Azure Subscription Name"

New-AzureRmResourceGroupDeployment -Name "deployment1" -ResourceGroupName "RG-DeploymentPacker1" -Templatefile "full path of your ARM JSON file generated by Packer" -TemplateParameterFile "full path to fichierparametres.parameters.json"

